# Generated by Django 3.2.7 on 2021-09-25 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_no', models.IntegerField(default=0, blank=True)),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField(null=True, blank=True)),
                ('quiz', models.JSONField(default=dict, null=True, blank=True)),
                ('materials', models.JSONField(default=dict, null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=3)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('enroll_start', models.DateTimeField()),
                ('enroll_end', models.DateTimeField()),
                ('class_size', models.IntegerField())
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.TextField(max_length=255)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=255)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_material', models.JSONField(default=list)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chapter')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
                ('quiz_response', models.JSONField(default=list, null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_main', to='api.course')),
                ('pre_requisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_requisite', to='api.course')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_chapter', models.PositiveSmallIntegerField(default=1, blank=True)),
                ('status', models.CharField(blank=True, choices=[('PD', 'Pending'), ('R', 'Rejected'), ('IP', 'In Progress'), ('P', 'Passed'), ('F', 'Failed'), ('W', 'Withdrawn')], default='PD', max_length=10)),
                ('course_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.classroom')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='pre_req',
            field=models.ManyToManyField(through='api.PreReq', to='api.Course'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.profile', null=True, blank=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='course_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.classroom'),
        ),
    ]
