# Generated by Django 3.2.7 on 2021-09-25 11:18

from django.db import migrations

def create_data(apps, schema_editor):
    Course = apps.get_model('api','Course')
    Course(course_name="Intro programming", description="Intro to programming").save()
    Course(course_name="Programming l", description="Intermediate programming").save()
    Course(course_name="Programming ll", description="Advanced programming").save()
    Course(course_name="Data", description="Intro Data").save()
    Course(course_name="Finance", description="Intro Finance").save()


    progintro = Course.objects.get(course_name="Intro programming")
    prog1 = Course.objects.get(course_name="Programming l")
    prog2 = Course.objects.get(course_name="Programming ll")

    prog1.pre_req.add(progintro)
    prog2.pre_req.add(prog1)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
