# Generated by Django 3.2.7 on 2021-09-25 12:40

from django.db import migrations

def create_data(apps, schema_editor):
    Profile = apps.get_model('api', 'Profile')
    Profile(username="rafeang", display_name="Rafe Ang").save()
    Profile(username="seantan", display_name="Sean Tan").save()
    Profile(username="charleslim", display_name="Charles Lim").save()
    Profile(username="shiqi", display_name="Shi Qi").save()
    Profile(username="yingting", display_name="Ying Ting").save()
    Profile(username="andre", display_name="Andre Lim", is_admin=True).save()
    Profile(username="nicholas", display_name="Nicholas Lim", is_admin=True).save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_course'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
