# Generated by Django 3.2.7 on 2021-09-25 13:20

from django.db import migrations

def create_data(apps, schema_editor):
    Enrollment = apps.get_model('api', 'Enrollment')
    Chapter = apps.get_model('api', 'Chapter')
    Profile = apps.get_model('api', 'Profile')
    Classroom = apps.get_model('api', 'Classroom')

    rafe = Profile.objects.get(username="rafeang")
    charles = Profile.objects.get(username="charleslim")
    shiqi = Profile.objects.get(username="shiqi")
    sean = Profile.objects.get(username="seantan")
    yingting = Profile.objects.get(username="yingting")

    intro_prog_g1 = Classroom.objects.get(class_name="g1", course_id=1)
    intro_prog_g2 = Classroom.objects.get(class_name="g2", course_id=1)

    prog1_g1 = Classroom.objects.get(class_name="g1", course_id=2)
    prog1_g2 = Classroom.objects.get(class_name="g2", course_id=2)

    prog2_g1 = Classroom.objects.get(class_name="g1", course_id=3)
    prog2_g2 = Classroom.objects.get(class_name="g2", course_id=3)

    prog3_g1 = Classroom.objects.get(class_name="g1", course_id=4)
    prog3_g2 = Classroom.objects.get(class_name="g2", course_id=4)

    prog4_g1 = Classroom.objects.get(class_name="g1", course_id=5)
    prog4_g2 = Classroom.objects.get(class_name="g2", course_id=5)

    Enrollment(username=rafe, course_class=intro_prog_g1, current_chapter=5, status="P").save()
    Enrollment(username=rafe, course_class=prog1_g2, current_chapter=5, status="IP").save()
    Enrollment(username=rafe, course_class=prog2_g1, current_chapter=2, status="IP").save()
    Enrollment(username=rafe, course_class=prog3_g2, status="F").save()
    Enrollment(username=rafe, course_class=prog4_g1, status="W").save()

    Enrollment(username=charles, course_class=intro_prog_g2, current_chapter=5, status="P").save()
    Enrollment(username=charles, course_class=prog1_g1, status="R").save()
    Enrollment(username=charles, course_class=prog3_g1, current_chapter=1, status="IP").save()
    Enrollment(username=charles, course_class=prog4_g2, status="R").save()

    Enrollment(username=shiqi, course_class=intro_prog_g1, current_chapter=1, status="IP").save()
    Enrollment(username=shiqi, course_class=prog3_g1, current_chapter=3, status="IP").save()
    Enrollment(username=shiqi, course_class=prog4_g1, current_chapter=5, status="IP").save()


    Enrollment(username=sean, course_class=intro_prog_g1, status="P").save()
    Enrollment(username=sean, course_class=prog1_g1, current_chapter=3, status="IP").save()
    Enrollment(username=sean, course_class=prog3_g2, current_chapter=3, status="IP").save()
    Enrollment(username=sean, course_class=prog4_g1, current_chapter=5, status="IP").save()

    Enrollment(username=yingting, course_class=intro_prog_g1, current_chapter=5, status="P").save()
    Enrollment(username=yingting, course_class=prog1_g2, current_chapter=5, status="P").save()
    Enrollment(username=yingting, course_class=prog2_g2, current_chapter=2, status="IP").save()
    Enrollment(username=yingting, course_class=prog3_g2, current_chapter=1, status="IP").save()
    Enrollment(username=yingting, course_class=prog4_g2, current_chapter=5, status="IP").save()



class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_chapter'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
