# Generated by Django 3.2.7 on 2021-09-25 13:30

from typing import final
from django.db import migrations

def create_data(apps, schema_editor):
    Progress = apps.get_model('api', 'Progress')
    Chapter = apps.get_model('api', 'Chapter')
    Profile = apps.get_model('api', 'Profile')

    rafe = Profile.objects.get(username="rafeang")
    charles = Profile.objects.get(username="charleslim")
    shiqi = Profile.objects.get(username="shiqi")
    sean = Profile.objects.get(username="seantan")
    yingting = Profile.objects.get(username="yingting")

    chap_prog_g1_1 = Chapter.objects.get(id=1)
    chap_prog_g1_2 = Chapter.objects.get(id=2)
    chap_prog_g1_3 = Chapter.objects.get(id=3)
    chap_prog_g1_4 = Chapter.objects.get(id=4)
    chap_prog_g1_5 = Chapter.objects.get(id=5)

    chap_prog_g2_1 = Chapter.objects.get(id=6)
    chap_prog_g2_2 = Chapter.objects.get(id=7)
    chap_prog_g2_3 = Chapter.objects.get(id=8)
    chap_prog_g2_4 = Chapter.objects.get(id=9)
    chap_prog_g2_5 = Chapter.objects.get(id=10)

    chap_prog1_g1_1 = Chapter.objects.get(id=11)
    chap_prog1_g1_2 = Chapter.objects.get(id=12)
    chap_prog1_g1_3 = Chapter.objects.get(id=13)

    chap_prog1_g2_1 = Chapter.objects.get(id=16)
    chap_prog1_g2_2 = Chapter.objects.get(id=17)
    chap_prog1_g2_3 = Chapter.objects.get(id=18)
    chap_prog1_g2_4 = Chapter.objects.get(id=19)
    chap_prog1_g2_5 = Chapter.objects.get(id=20)

    chap_prog2_g1_1 = Chapter.objects.get(id=21)
    chap_prog2_g1_2 = Chapter.objects.get(id=22)

    chap_prog2_g2_1 = Chapter.objects.get(id=25)
    chap_prog2_g2_2 = Chapter.objects.get(id=26)

    chap_data_g1_1 = Chapter.objects.get(id=28)
    chap_data_g1_2 = Chapter.objects.get(id=29)
    chap_data_g1_3 = Chapter.objects.get(id=30)

    chap_data_g2_1 = Chapter.objects.get(id=33)
    chap_data_g2_2 = Chapter.objects.get(id=34)
    chap_data_g2_3 = Chapter.objects.get(id=35)

    chap_finance_g1_1 = Chapter.objects.get(id=38)
    chap_finance_g1_2 = Chapter.objects.get(id=39)
    chap_finance_g1_3 = Chapter.objects.get(id=40)
    chap_finance_g1_4 = Chapter.objects.get(id=41)
    chap_finance_g1_5 = Chapter.objects.get(id=42)

    chap_finance_g2_1 = Chapter.objects.get(id=43)
    chap_finance_g2_2 = Chapter.objects.get(id=44)
    chap_finance_g2_3 = Chapter.objects.get(id=45)
    chap_finance_g2_4 = Chapter.objects.get(id=46)
    chap_finance_g2_5 = Chapter.objects.get(id=47)
    
    completed_material = {
            "firebase.starge.url1": True,
            "firebase.starge.url2": True,
            "firebase.starge.url3": True,
            "firebase.starge.url4": True
        }


    material = {
            "firebase.starge.url1": True,
            "firebase.starge.url2": False,
            "firebase.starge.url3": True,
            "firebase.starge.url4": False
        }
    
    quizReponse = { 
        "questions": {
            1: {
                "response": "Yes",
                "correct_answer": "Yes",
                "correct": True
            },
            2: {
                "response": "All of the above",
                "correct_answer": "All of the above",
                "correct": True
            }
        },
        "score": 2,
        "total_score": 2
    }
   
    Progress(learner=rafe, chapter=chap_prog_g1_1, completed_material=completed_material,  quiz_response=quizReponse).save()
    Progress(learner=rafe, chapter=chap_prog_g1_2, completed_material=completed_material,  quiz_response=quizReponse).save()
    Progress(learner=rafe, chapter=chap_prog_g1_3, completed_material=completed_material,  quiz_response=quizReponse).save()
    Progress(learner=rafe, chapter=chap_prog_g1_4, completed_material=completed_material,  quiz_response=quizReponse).save()
    Progress(learner=rafe, chapter=chap_prog_g1_5, completed_material=completed_material,  quiz_response=quizReponse).save()

    Progress(learner=sean, chapter=chap_prog_g1_1, completed_material=completed_material,  quiz_response=quizReponse).save()
    Progress(learner=sean, chapter=chap_prog_g1_2, completed_material=completed_material,  quiz_response=quizReponse).save()
    Progress(learner=sean, chapter=chap_prog_g1_3, completed_material=completed_material,  quiz_response=quizReponse).save()
    Progress(learner=sean, chapter=chap_prog_g1_4, completed_material=completed_material,  quiz_response=quizReponse).save()
    Progress(learner=sean, chapter=chap_prog_g1_5, completed_material=completed_material,  quiz_response=quizReponse).save()

    Progress(learner=yingting, chapter=chap_prog_g1_1, completed_material=completed_material,  quiz_response=quizReponse).save()
    Progress(learner=yingting, chapter=chap_prog_g1_2, completed_material=completed_material,  quiz_response=quizReponse).save()
    Progress(learner=yingting, chapter=chap_prog_g1_3, completed_material=completed_material,  quiz_response=quizReponse).save()
    Progress(learner=yingting, chapter=chap_prog_g1_4, completed_material=completed_material,  quiz_response=quizReponse).save()
    Progress(learner=yingting, chapter=chap_prog_g1_5, completed_material=completed_material,  quiz_response=quizReponse).save()

    Progress(learner=shiqi, chapter=chap_prog_g1_1, completed_material=material).save()

    Progress(learner=charles, chapter=chap_prog_g2_1, completed_material=completed_material,  quiz_response=quizReponse).save()
    Progress(learner=charles, chapter=chap_prog_g2_2, completed_material=completed_material,  quiz_response=quizReponse).save()
    Progress(learner=charles, chapter=chap_prog_g2_3, completed_material=completed_material,  quiz_response=quizReponse).save()
    Progress(learner=charles, chapter=chap_prog_g2_4, completed_material=completed_material,  quiz_response=quizReponse).save()
    Progress(learner=charles, chapter=chap_prog_g2_5, completed_material=completed_material,  quiz_response=quizReponse).save()

    
    Progress(learner=sean, chapter=chap_prog1_g1_1, completed_material=completed_material,  quiz_response=quizReponse).save()
    Progress(learner=sean, chapter=chap_prog1_g1_2, completed_material=completed_material,  quiz_response=quizReponse).save()
    Progress(learner=sean, chapter=chap_prog1_g1_3, completed_material=material).save()

    Progress(learner=rafe, chapter=chap_prog1_g2_1, completed_material=completed_material,  quiz_response=quizReponse).save()
    Progress(learner=rafe, chapter=chap_prog1_g2_2, completed_material=completed_material,  quiz_response=quizReponse).save()
    Progress(learner=rafe, chapter=chap_prog1_g2_3, completed_material=completed_material,  quiz_response=quizReponse).save()
    Progress(learner=rafe, chapter=chap_prog1_g2_4, completed_material=completed_material,  quiz_response=quizReponse).save()
    Progress(learner=rafe, chapter=chap_prog1_g2_5, completed_material=completed_material,  quiz_response=quizReponse).save()

    Progress(learner=yingting, chapter=chap_prog1_g2_1, completed_material=completed_material,  quiz_response=quizReponse).save()
    Progress(learner=yingting, chapter=chap_prog1_g2_2, completed_material=completed_material,  quiz_response=quizReponse).save()
    Progress(learner=yingting, chapter=chap_prog1_g2_3, completed_material=completed_material,  quiz_response=quizReponse).save()
    Progress(learner=yingting, chapter=chap_prog1_g2_4, completed_material=completed_material,  quiz_response=quizReponse).save()
    Progress(learner=yingting, chapter=chap_prog1_g2_5, completed_material=completed_material,  quiz_response=quizReponse).save()

    Progress(learner=rafe, chapter=chap_prog2_g1_1, completed_material=completed_material,  quiz_response=quizReponse).save()
    Progress(learner=rafe, chapter=chap_prog2_g1_2, completed_material=material).save()

    Progress(learner=yingting, chapter=chap_prog2_g2_1, completed_material=completed_material,  quiz_response=quizReponse).save()
    Progress(learner=yingting, chapter=chap_prog2_g2_2, completed_material=completed_material).save()


    Progress(learner=shiqi, chapter=chap_data_g1_1, completed_material=completed_material,  quiz_response=quizReponse).save()
    Progress(learner=shiqi, chapter=chap_data_g1_2, completed_material=completed_material,  quiz_response=quizReponse).save()
    Progress(learner=shiqi, chapter=chap_data_g1_3, completed_material=material).save()

    Progress(learner=charles, chapter=chap_data_g1_1, completed_material=material).save()

    Progress(learner=sean, chapter=chap_data_g2_1, completed_material=completed_material,  quiz_response=quizReponse).save()
    Progress(learner=sean, chapter=chap_data_g2_2, completed_material=completed_material,  quiz_response=quizReponse).save()
    Progress(learner=sean, chapter=chap_data_g2_3, completed_material=material).save()

    Progress(learner=yingting, chapter=chap_data_g2_1, completed_material=material).save()

    Progress(learner=shiqi, chapter=chap_finance_g1_1, completed_material=completed_material,  quiz_response=quizReponse).save()
    Progress(learner=shiqi, chapter=chap_finance_g1_2, completed_material=completed_material,  quiz_response=quizReponse).save()
    Progress(learner=shiqi, chapter=chap_finance_g1_3, completed_material=completed_material,  quiz_response=quizReponse).save()
    Progress(learner=shiqi, chapter=chap_finance_g1_4, completed_material=completed_material,  quiz_response=quizReponse).save()
    Progress(learner=shiqi, chapter=chap_finance_g1_5, completed_material=completed_material,  quiz_response=quizReponse).save()

    Progress(learner=sean, chapter=chap_finance_g1_1, completed_material=completed_material,  quiz_response=quizReponse).save()
    Progress(learner=sean, chapter=chap_finance_g1_2, completed_material=completed_material,  quiz_response=quizReponse).save()
    Progress(learner=sean, chapter=chap_finance_g1_3, completed_material=completed_material,  quiz_response=quizReponse).save()
    Progress(learner=sean, chapter=chap_finance_g1_4, completed_material=completed_material,  quiz_response=quizReponse).save()
    Progress(learner=sean, chapter=chap_finance_g1_5, completed_material=completed_material,  quiz_response=quizReponse).save()

    Progress(learner=yingting, chapter=chap_finance_g2_1, completed_material=completed_material,  quiz_response=quizReponse).save()
    Progress(learner=yingting, chapter=chap_finance_g2_2, completed_material=completed_material,  quiz_response=quizReponse).save()
    Progress(learner=yingting, chapter=chap_finance_g2_3, completed_material=completed_material,  quiz_response=quizReponse).save()
    Progress(learner=yingting, chapter=chap_finance_g2_4, completed_material=completed_material,  quiz_response=quizReponse).save()
    Progress(learner=yingting, chapter=chap_finance_g2_5, completed_material=completed_material,  quiz_response=quizReponse).save()
   

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_enrollment'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
