# Generated by Django 3.2.7 on 2021-10-06 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_progress'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('course_class', 'username'), name='enrollment_cpk'),
        ),
    ]
