# Generated by Django 3.2.7 on 2021-10-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20211006_1301'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(
                fields=('course', 'course_class', 'chapter_no'), name='chapter_cpk'),
        ),
    ]
